//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_PROJECT
    {
        public int Client_project_ID { get; set; }
        public int Client_ID { get; set; }
        public int Project_ID { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Last_update_by { get; set; }
        public decimal Payment { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
