//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERABLE()
        {
            this.EMPLOYEE_DELIVERABLE = new HashSet<EMPLOYEE_DELIVERABLE>();
            this.TIMESHEETs = new HashSet<TIMESHEET>();
        }
    
        public int Deliverable_ID { get; set; }
        public System.DateTime Deliverable_deadline { get; set; }
        public Nullable<System.DateTime> Deliverable_end_date { get; set; }
        public System.DateTime Deliverable_start_date { get; set; }
        public string Name { get; set; }
        public decimal Budget { get; set; }
        public int Estimated_manhours { get; set; }
        public int Manhours_charged { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Last_update_by { get; set; }
        public int Project_ID { get; set; }
        public string Progress_status { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLOYEE_DELIVERABLE> EMPLOYEE_DELIVERABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMESHEET> TIMESHEETs { get; set; }
    }
}
