//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_DELIVERABLE
    {
        public int Employee_deliverable_ID { get; set; }
        public int Employee_ID { get; set; }
        public int Deliverable_ID { get; set; }
        public double Hours_worked { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Last_update_by { get; set; }
    
        public virtual DELIVERABLE DELIVERABLE { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
