//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT()
        {
            this.CLIENT_PROJECT = new HashSet<CLIENT_PROJECT>();
            this.DELIVERABLES = new HashSet<DELIVERABLE>();
        }
    
        public string Name { get; set; }
        public int Project_ID { get; set; }
        public string USA_region { get; set; }
        public System.DateTime Deadline { get; set; }
        public decimal Budget { get; set; }
        public System.DateTime Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public string Progress_status { get; set; }
        public System.DateTime Last_update { get; set; }
        public string Last_update_by { get; set; }
        public int Department_ID { get; set; }
        public int Manager_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENT_PROJECT> CLIENT_PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERABLE> DELIVERABLES { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
